### ISSUE TITLE
Adding local files storage for animes.

### ISSUE THREAD

**Issue by thisisme345** [AlexArtaud-Dev/MangAnime#1]
Will you do another file but for local files storage?

**Comment by AlexArtaud-Dev** [comment]
To answer you, i already had this idea in my mind before starting this project.
So before MangAnime, i created another project that was a website with a server reading your files from any drive you wanted,
then indexing everything, gathering data for each (movie/series, animes...), storing them and making them available on the website.
Then a video player was able to play the video from your drive directly to the web (like a NAS would do with Plex).
The fact is, i never ended it, and i don't have the time for it right now.
The major issus was it was not very reliable for the movie/anime information gathering, and it was slow.
If you want, i can send this projet to you via discord. Do not hesitate to DM me : |Alex|#3227

**Comment by AlexArtaud-Dev** [comment]
Also, if you want to test MangAnime, 
Here is a key to register : 82T5EQQ-55S4P9G-K9EAR0A-BDMHC6A
https://www.manganimes.me/

**Comment by AlexArtaud-Dev** [comment]
To answer you properly, i think that i will make another project to allow file reading on browser with information gathering.
But i'll do it using another language that i got to learn (C#) since it seems apropriate for this project.
